export const GET_CHARACTERS_INIT = 'GET_CHARACTERS_INIT'
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS'
export const GET_CHARACTERS_ERROR = 'GET_CHARACTERS_ERROR'
export const CLEAN_CHARACTERS = 'CLEAN_CHARACTERS'
